language: node_js

node_js:
  - 'stable'

cache:
  directories:
    - node_modules # NPM packages

branches:
  only:
    - master

before_script:
  - yarn global add firebase-tools
  - yarn

script:
  - yarn build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
